apiVersion: v1
kind: ConfigMap
metadata:
  name: color-config
data:
  red.html: |
    <h1><font color="red">The Color is Red</font></h1>
  green.html: |
    <h1><font color="green">The Color is Green</font></h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-red
  labels:
    app: nginx-red
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-red
  template:
    metadata:
      labels:
        app: nginx-red
    spec:
      containers:
        - name: nginx-red
          image: nginx:1.19
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-files
              mountPath: /usr/share/nginx/html/red
      volumes:
        - name: html-files
          configMap:
            name: color-config
            items:
              - key: red.html
                path: index.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-green
  labels:
    app: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-green
  template:
    metadata:
      labels:
        app: nginx-green
    spec:
      containers:
        - name: nginx-green
          image: nginx:1.19
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-files
              mountPath: /usr/share/nginx/html/green
      volumes:
        - name: html-files
          configMap:
            name: color-config
            items:
              - key: green.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-red-svc
  labels:
    app: nginx-red
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-red
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-green-svc
  labels:
    app: nginx-green
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-green
